package ReverseModule;


/**
* ReverseModule/ReverseOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ReverseModule.idl
* Sunday, May 7, 2023 8:24:45 AM GMT
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
